steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/storybook-frontend', '--build-arg', 'VITE_API_URL=$_VITE_API_URL', '-f', 'web-ui/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storybook-frontend']
images:
  - 'gcr.io/$PROJECT_ID/storybook-frontend'
